/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.Game;

import Main.*;
import javax.swing.JOptionPane;

/**
 *
 * @author TheOneAboveAll
 */
public class JFGameS extends javax.swing.JFrame {
    private String player1; //Nombre de los jugadores
    private String player2;
    
    private int player1Points = 0;
    private int player2Points = 0;
    private int intentosP1 = 6;
    private int intentosP2 = 6;
    public int turno = 0;
    public boolean permiso = true;
    public int count = 0;
    /*
    El primer espacio del arreglo se encuentra la pala que el jugador eligio como la pista, 
    los siguientes 6 espacios se encuentran las 6 palabras que el jugador va escribiendo en cada uno de sus 
    intentos
    */
    public String[] wordsPlayer1 = new String[8];
    public String[] wordsPlayer2 = new String[8];
    
    //GETTERS Y SETTERSSS
    public void setPlayer1(String n){   this.player1 = n;  }
    public void setPlayer2(String n){   this.player2 = n;  }
    public void setPlayer1Points(int x){   this.player1Points = x;  }
    public void setPlayer2Points(int x){   this.player2Points = x;  }
    
    public String getPlayer1(){   return this.player1;  }
    public String getPlayer2(){   return this.player2;  }
    public int getPlayer1Points(){   return this.player1Points;  }
    public int getPlayer2Points(){   return this.player2Points;  }
    /**
     * Creates new form JFGameS
     */
    public JFGameS(String p1, String p2) {
        initComponents();
        
        this.setPlayer1(p1);
        this.setPlayer2(p2);
        
        //System.out.println("jugador 1: " + this.getPlayer1());
        
        jTFShowNameP1.setText(p1);
        jTFShowNameP2.setText(p2);
        
        //Se colocan los puntajes de cada uno de los jugadores
        jTFShowPointsP1.setText(this.getPlayer1Points() + "");
        jTFShowPointsP2.setText(this.getPlayer2Points() + "");
        
        //Se coloca el nombre del jugador en turno
        jTFShowPlayerTurn.setText(this.getPlayer1());
        
        
        
       
    }
    public JFGameS(int t, String sw, String p){
        if(t == 0){
            this.wordsPlayer1[0] = sw; this.wordsPlayer1[1] = p;
        }else{
            this.wordsPlayer2[0] = sw; this.wordsPlayer2[1] = p;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBShowManual = new javax.swing.JButton();
        jTFShowNameP1 = new javax.swing.JLabel();
        jTFShowNameP2 = new javax.swing.JLabel();
        jTFShowPointsP2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFShowPointsP1 = new javax.swing.JLabel();
        jBPlayGame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTFShowPlayerTurn = new javax.swing.JLabel();
        jTFShowWordsP1 = new javax.swing.JLabel();
        jTFShowWordsP2 = new javax.swing.JLabel();
        jTFShowPista = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User1.jpg"))); // NOI18N
        jLabel8.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User2.jpg"))); // NOI18N
        jLabel7.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("JUGADOR 1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("JUGADOR 2");

        jBShowManual.setText("Mostrar el manual");

        jTFShowNameP1.setBackground(new java.awt.Color(255, 51, 51));
        jTFShowNameP1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowNameP1.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowNameP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowNameP1.setOpaque(true);

        jTFShowNameP2.setBackground(new java.awt.Color(255, 51, 51));
        jTFShowNameP2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowNameP2.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowNameP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowNameP2.setOpaque(true);

        jTFShowPointsP2.setBackground(new java.awt.Color(255, 255, 255));
        jTFShowPointsP2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowPointsP2.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowPointsP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowPointsP2.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Puntos:");

        jTFShowPointsP1.setBackground(new java.awt.Color(255, 255, 255));
        jTFShowPointsP1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowPointsP1.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowPointsP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowPointsP1.setOpaque(true);

        jBPlayGame.setText("Ingresar palabra secreta y pista");
        jBPlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlayGameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Turno del jugador:");

        jTFShowPlayerTurn.setBackground(new java.awt.Color(255, 255, 255));
        jTFShowPlayerTurn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowPlayerTurn.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowPlayerTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowPlayerTurn.setOpaque(true);

        jTFShowWordsP1.setBackground(new java.awt.Color(255, 255, 255));
        jTFShowWordsP1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowWordsP1.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowWordsP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowWordsP1.setOpaque(true);

        jTFShowWordsP2.setBackground(new java.awt.Color(255, 255, 255));
        jTFShowWordsP2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTFShowWordsP2.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowWordsP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowWordsP2.setOpaque(true);

        jTFShowPista.setBackground(new java.awt.Color(255, 255, 255));
        jTFShowPista.setForeground(new java.awt.Color(0, 0, 0));
        jTFShowPista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTFShowPista.setOpaque(true);
        jTFShowPista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFShowPistaMouseClicked(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Palabra secreta:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Pista:");

        jPasswordField2.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFShowNameP1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFShowWordsP1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jBShowManual))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jTFShowPointsP1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTFShowPointsP2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jTFShowPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jTFShowPista, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFShowWordsP2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBPlayGame)
                                .addGap(169, 169, 169))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(122, 122, 122)))
                        .addComponent(jTFShowNameP2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(390, 390, 390)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(648, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFShowWordsP2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBShowManual)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFShowPointsP1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFShowPointsP2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFShowPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBPlayGame)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jTFShowNameP1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addComponent(jTFShowNameP2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jTFShowWordsP1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFShowPista, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(375, 375, 375)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(435, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlayGameActionPerformed
        
        switch(this.turno){
            //Si es 0 es turno del jugador 1, si es 1 es turno del jugador 2
            case 0:
                
                //Se valida el permiso para que se active la case SecretWords y se inserte la palaba secreta y la pista 
                if(this.permiso){
                    JFSecretWords secretWords = new JFSecretWords(this.getPlayer1(), 0); //Se inserta el nombre del jugador en turno en la case SecretWords
                    
                    
                    secretWords.setVisible(true);
                    secretWords.setLocationRelativeTo(null);
                    
                    this.permiso = false;
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Accion invalida, espere a laconclución del turno del jugador");
                }
                
                
                break;
            
            case 1: 
                 if(this.permiso){
                    JFSecretWords secretWords = new JFSecretWords(this.getPlayer2(), 1);
                    secretWords.playerName = this.getPlayer2();
                    secretWords.setVisible(true);
                    secretWords.setLocationRelativeTo(null);
                    this.permiso = false;
                } else {
                    JOptionPane.showMessageDialog(null, "Accion invalida, espere a laconclución del turno del jugador");
                }
                break;
                
            default: 
                
                break;
        }
        
        
        
        
        
    }//GEN-LAST:event_jBPlayGameActionPerformed

    private void jTFShowPistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFShowPistaMouseClicked
        jTFShowPista.setText(this.wordsPlayer1[1]);
        //jTFShowPista.setText("funciona");
        
        
    }//GEN-LAST:event_jTFShowPistaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGameS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGameS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGameS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGameS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPlayGame;
    private javax.swing.JButton jBShowManual;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel jTFShowNameP1;
    private javax.swing.JLabel jTFShowNameP2;
    private javax.swing.JLabel jTFShowPista;
    private javax.swing.JLabel jTFShowPlayerTurn;
    private javax.swing.JLabel jTFShowPointsP1;
    private javax.swing.JLabel jTFShowPointsP2;
    private javax.swing.JLabel jTFShowWordsP1;
    private javax.swing.JLabel jTFShowWordsP2;
    // End of variables declaration//GEN-END:variables
}
